### ISSUE TITLE
Label and other subcomponent labels not shown correctly on android devices

### ISSUE THREAD

**Issue by rzv86** [BowlerHatLLC/feathersui-starling#1795]
This happens on labels, all kind of labels (buttons, trees, etc), on devices with android >=7.0 

![ss](https://user-images.githubusercontent.com/18426095/67045341-c197f480-f136-11e9-8f53-cb18bace95c0.jpg)

Labels are shifted down on my samsung s8 (android 7), samsung s8 (android 9) and lenovo tab p10 (android 9), using air sdk 32, starling 2.5.1, feathers 4.0. This happens even on older air sdk / starling versions and feathers 3.5.
However, this doesn't happen on my older devices samsung note p-600(android 5.1.1) and huawei mediapad m2 10(android 5.1.1).  

TextFields and Buttons from starling are displayed correctly on all platforms.

I've tried many solutions, none to work. 
One workaround is setting paddingTop = - x, but it's not ok because this value is related to textFormat size and must be adjusted accordingly to it's size, 
e.g: so if we have a text size of 16, paddingTop is ~ -4,  if we set text size to 60, then paddingTop must be ~ -20.
Also, the device's resolution has something to do with it because labels are shifted down differently on my mobile devices.
 
Thank you,

**Comment by joshtynjala** [comment]
Are you using an embedded font? Which text renderer are you using?

**Comment by rzv86** [comment]
I'm using embedded fonts from my .fla library.
The default text renderer, I didn't set any.

**Comment by joshtynjala** [comment]
You might try using a different font to see if that makes a difference. It's been my experience that some fonts don't properly report their measurements, and it can lead to issues like these.

**Comment by joshtynjala** [comment]
If you're using a font embedded in a *.fla* file, then you're probably not using the default text renderer, which is BitmapFontTextRenderer. Embedded fonts are compatible with either TextFieldTextRenderer or TextBlockTextRenderer.

**Comment by rzv86** [comment]
I'm using metalworks mobile theme with some little adjustments on object's colors.

I need to embedd arial bold and regular in my app, but I don't know how to obtain them. 
Can you please help me with those? Or maybe point me to some reference documentation. 

My app has landscape aspect ratio set, I've mentioned it just in case..

**Comment by joshtynjala** [comment]
MetalWorksMobileTheme uses TextBlockTextRenderer.

When you embed a font in the library of your *.fla* file, you need to set its **Outline format** to **FTE (DF4)** to be compatible with TextBlockTextRenderer. If it is embedded as _Classic (DF3)_, TextBlockTextRenderer won't use it.

**Comment by rzv86** [comment]
Worked like a charm!! 

Thanks a lot for your help!

I am having trouble with another problem, but I'm sure that has nothing to do with feathers.
All my input texts which are initially positioned bellow keyboard (bellow half stage) are not shown after keyboard appears.  TextInput case (background) is displayed but not the text that I had typed in it.
I've tried with flash stageText and it's the same problem.

**Comment by urthling** [comment]
Not sure if this helps - sounds like you might already know how to embed the fonts - in terms of downloading available fonts - there are a number of sources online that will give you the ttf fonts you're looking for.


`[Embed(source="assets/fonts/somefont.ttf", 				fontFamily="somefamilyname", 		mimeType="application/x-font", embedAsCFF="false")] public static const SomeFont 					:Class;`

The above path places the assets folder directly under /src -- reference fontFamily to use the embedded font.

```
label.textRendererFactory = function():ITextRenderer
{
	var renderer 	:TextFieldTextRenderer 	= new TextFieldTextRenderer();

	renderer.embedFonts 			   = true;
	return renderer;
}
```
`label.fontStyles 	= new starling.text.TextFormat( "somefamilyname", fontSize.......`

**Comment by joshtynjala** [comment]
@rzv86 Great! I recommend moving further discussion to: https://forum.starling-framework.org.

You'll get a little more visibility from the community, so it's not just me answering questions.
