### ISSUE TITLE
LayoutGroup visible property

### ISSUE THREAD

**Issue by urthling** [BowlerHatLLC/feathersui-starling#1803]
Thank you for getting 4.1.0 out!!!

I use a showEffect and hideEffect on a layoutGroup to tween some components on and off stage.

Since updating to 4.1.0 -- when programmatically setting the visible property of a layoutGroup to false, the hideEffect fires as expected, but the layoutGroup visible property remains true..

**Comment by joshtynjala** [comment]
I could reproduce the issue, and it is now fixed.

**Comment by urthling** [comment]
Should the installer be including these updates (not seeing at mo), or should I build from source for now?

**Comment by joshtynjala** [comment]
No, the updates are not included in the SDK installer. It will require a full release, which takes hours. For now, to get the fix, it needs to built from source. The fix is also not yet merged into the "mxml" branch, which is a special branch of the main library that the SDK uses.

**Comment by urthling** [comment]
Gotcha -- I'm just jazzed you've had time to release 4.1, so, power to you.

**Comment by urthling** [comment]
Unfortunately, I can't build from source on my machine -- I just ran the installer again and noticed the updates are not baked in yet -- do you know when this might be done?  ty in advance!!

**Comment by joshtynjala** [comment]
I do not know when I will have the chance to release the next update. Maybe in the next month.

**Comment by urthling** [comment]
Checking in - hope you're safe and well!

**Comment by urthling** [comment]
I'm planning a release for the App soon and it would be great to be able to use 4.1!

**Comment by joshtynjala** [comment]
@urthling I released v4.1.1 today with the fix.

**Comment by urthling** [comment]
..and I can confirm its working like a charm!
