### ISSUE TITLE
SoundChannelPeakVisualizer Implementation

### ISSUE THREAD

**Issue by jam65st** [BowlerHatLLC/feathersui-starling#1805]
Hi, is possible that you publish an example about the Class: *SoundChannelPeakVisualizer* implementation and skinning.

Thanks a lot in advance.

**Comment by joshtynjala** [comment]
I believe that you need to set the width and height and add it to your VideoPlayer or SoundPlayer.

```as3
var peaks:SoundChannelPeakVisualizer = new SoundChannelPeakVisualizer();
peaks.width = 20;
peaks.height = 100;
mediaPlayer.addChild(peaks);
```

Looking over the code, the `gap` is the only styling property, to set the number of pixels between the two bars. The two bars are just white quads, and it looks like I never exposed a way to change their colors.

**Comment by jam65st** [comment]
Hi @joshtynjala, this _powerful feature_ is not documented and included in the *FeathersUI themes*. Its use is as described, but when compiling only a thin white line appears.

I apologize for the delay in responding, I jump a few days between projects but I need to thank you for the immense effort you have made to keep this technology alive.
