### ISSUE TITLE
Default scale factor of MetalWorksDesktopTheme?

### ISSUE THREAD

**Issue by hoangdung-qbt** [BowlerHatLLC/feathersui-starling#1809]
Hi! Josh. I just found it in https://github.com/BowlerHatLLC/feathersui-starling/blob/master/themes/MetalWorksDesktopTheme/source/feathers/themes/MetalWorksDesktopTheme.as
**protected static const ATLAS_SCALE_FACTOR:int = 2;**
I was developing an educational app for teachers that runs on PC and Mac. my app just uses 1x texture. Starling stage is always set to 1138x640px even with full screen mode. I did some test on my PC (2k - 1920 x 1080), everything worked fine. For example:
```
pickerList.width = 150;
pickerList.height = 30;
```
The pickerList shows up with correct size!. But my concern is in 4k screen (higher DPI), it will pick 2x textures and the pickerList will be bigger. Correct me if i am wrong. Just my little question about the default scale factor of Feathers themes. It is set to 1  or automatically set to 2 on high resolution screen (4k,8k....)?
Thanks in advance.

**Comment by joshtynjala** [comment]
Starling's scaling system is really smart. Even if the texture's scale factor is not the same as the device's scale factor, that's okay. Starling will ensure that the texture displays at the same size on all device scale factors. How easy Starling makes this is one of my favorite things about the library.
